import type { RowanAlert } from "../types/alert/alert.js";
import type { RowanAccordion } from "../types/accordion/accordion.js";
import type { RowanAvatar } from "../types/avatar/avatar.js";
import type { RowanBadge } from "../types/badge/badge.js";
import type { RowanBreadcrumb } from "../types/breadcrumb/breadcrumb.js";
import type { RowanBulkActionsBar } from "../types/bulk-actions-bar/bulk-actions-bar.js";
import type { RowanButton } from "../types/button/button.js";
import type { RowanFilterBuilder } from "../types/filter-builder/filter-builder.js";
import type { RowanCalendar } from "../types/calendar/calendar.js";
import type { RowanCard } from "../types/card/card.js";
import type { RowanCheckbox } from "../types/checkbox/checkbox.js";
import type { RowanChip } from "../types/chip/chip.js";
import type { RowanCombobox } from "../types/combobox/combobox.js";
import type { RowanCommandItem } from "../types/command-item/command-item.js";
import type { RowanCommandPalette } from "../types/command-palette/command-palette.js";
import type { RowanDatePicker } from "../types/date-picker/date-picker.js";
import type { RowanDateRangePicker } from "../types/date-range-picker/date-range-picker.js";
import type { RowanDivider } from "../types/divider/divider.js";
import type { RowanDialog } from "../types/dialog/dialog.js";
import type { RowanDropzone } from "../types/dropzone/dropzone.js";
import type { RowanDrawer } from "../types/drawer/drawer.js";
import type { RowanDropdown } from "../types/dropdown/dropdown.js";
import type { RowanEmptyState } from "../types/empty-state/empty-state.js";
import type { RowanFileItem } from "../types/file-item/file-item.js";
import type { RowanFileUpload } from "../types/file-upload/file-upload.js";
import type { RowanFormField } from "../types/form-field/form-field.js";
import type { RowanFormLayout } from "../types/form-layout/form-layout.js";
import type { RowanFormWizard } from "../types/form-wizard/form-wizard.js";
import type { RowanIconButton } from "../types/icon-button/icon-button.js";
import type { RowanLink } from "../types/link/link.js";
import type { RowanListbox } from "../types/listbox/listbox.js";
import type { RowanMenu } from "../types/menu/menu.js";
import type { RowanMenuItem } from "../types/menu-item/menu-item.js";
import type { RowanMultiSelectCombobox } from "../types/multi-select-combobox/multi-select-combobox.js";
import type { RowanNumberField } from "../types/number-field/number-field.js";
import type { RowanOption } from "../types/option/option.js";
import type { RowanPagination } from "../types/pagination/pagination.js";
import type { RowanPopover } from "../types/popover/popover.js";
import type { RowanProgress } from "../types/progress/progress.js";
import type { RowanRadio } from "../types/radio/radio.js";
import type { RowanRadioGroup } from "../types/radio-group/radio-group.js";
import type { RowanRowDetailsPanel } from "../types/row-details-panel/row-details-panel.js";
import type { RowanSelect } from "../types/select/select.js";
import type { RowanSegmentedControl } from "../types/segmented-control/segmented-control.js";
import type { RowanSkeleton } from "../types/skeleton/skeleton.js";
import type { RowanSlider } from "../types/slider/slider.js";
import type { RowanSpinner } from "../types/spinner/spinner.js";
import type { RowanStepper } from "../types/stepper/stepper.js";
import type { RowanSwitch } from "../types/switch/switch.js";
import type { RowanTab } from "../types/tab/tab.js";
import type { RowanTabPanel } from "../types/tab-panel/tab-panel.js";
import type { RowanTable } from "../types/table/table.js";
import type { RowanTableToolbar } from "../types/table-toolbar/table-toolbar.js";
import type { RowanTabs } from "../types/tabs/tabs.js";
import type { RowanTree } from "../types/tree/tree.js";
import type { RowanTreeItem } from "../types/tree-item/tree-item.js";
import type { RowanTextField } from "../types/text-field/text-field.js";
import type { RowanTextarea } from "../types/textarea/textarea.js";
import type { RowanTimePicker } from "../types/time-picker/time-picker.js";
import type { RowanToast } from "../types/toast/toast.js";
import type { RowanToaster } from "../types/toaster/toaster.js";
import type { RowanTooltip } from "../types/tooltip/tooltip.js";
import type { RowanValidationSummary } from "../types/validation-summary/validation-summary.js";
import type { RowanVirtualList } from "../types/virtual-list/virtual-list.js";

declare global {
  interface HTMLElementTagNameMap {
    "rowan-accordion": RowanAccordion;
    "rowan-alert": RowanAlert;
    "rowan-avatar": RowanAvatar;
    "rowan-badge": RowanBadge;
    "rowan-breadcrumb": RowanBreadcrumb;
    "rowan-bulk-actions-bar": RowanBulkActionsBar;
    "rowan-button": RowanButton;
    "rowan-filter-builder": RowanFilterBuilder;
    "rowan-calendar": RowanCalendar;
    "rowan-card": RowanCard;
    "rowan-checkbox": RowanCheckbox;
    "rowan-chip": RowanChip;
    "rowan-combobox": RowanCombobox;
    "rowan-command-item": RowanCommandItem;
    "rowan-command-palette": RowanCommandPalette;
    "rowan-date-picker": RowanDatePicker;
    "rowan-date-range-picker": RowanDateRangePicker;
    "rowan-divider": RowanDivider;
    "rowan-dialog": RowanDialog;
    "rowan-dropzone": RowanDropzone;
    "rowan-drawer": RowanDrawer;
    "rowan-dropdown": RowanDropdown;
    "rowan-empty-state": RowanEmptyState;
    "rowan-file-item": RowanFileItem;
    "rowan-file-upload": RowanFileUpload;
    "rowan-form-field": RowanFormField;
    "rowan-form-layout": RowanFormLayout;
    "rowan-form-wizard": RowanFormWizard;
    "rowan-icon-button": RowanIconButton;
    "rowan-link": RowanLink;
    "rowan-listbox": RowanListbox;
    "rowan-menu": RowanMenu;
    "rowan-menu-item": RowanMenuItem;
    "rowan-multi-select-combobox": RowanMultiSelectCombobox;
    "rowan-number-field": RowanNumberField;
    "rowan-option": RowanOption;
    "rowan-pagination": RowanPagination;
    "rowan-popover": RowanPopover;
    "rowan-progress": RowanProgress;
    "rowan-radio": RowanRadio;
    "rowan-radio-group": RowanRadioGroup;
    "rowan-row-details-panel": RowanRowDetailsPanel;
    "rowan-select": RowanSelect;
    "rowan-segmented-control": RowanSegmentedControl;
    "rowan-skeleton": RowanSkeleton;
    "rowan-slider": RowanSlider;
    "rowan-spinner": RowanSpinner;
    "rowan-stepper": RowanStepper;
    "rowan-switch": RowanSwitch;
    "rowan-tab": RowanTab;
    "rowan-tab-panel": RowanTabPanel;
    "rowan-table": RowanTable;
    "rowan-table-toolbar": RowanTableToolbar;
    "rowan-tabs": RowanTabs;
    "rowan-tree": RowanTree;
    "rowan-tree-item": RowanTreeItem;
    "rowan-text-field": RowanTextField;
    "rowan-textarea": RowanTextarea;
    "rowan-time-picker": RowanTimePicker;
    "rowan-toast": RowanToast;
    "rowan-toaster": RowanToaster;
    "rowan-tooltip": RowanTooltip;
    "rowan-validation-summary": RowanValidationSummary;
    "rowan-virtual-list": RowanVirtualList;
  }
}

export {};
