import type { RowanAlert } from "./alert/alert.js";
import type { RowanAccordion } from "./accordion/accordion.js";
import type { RowanAvatar } from "./avatar/avatar.js";
import type { RowanBadge } from "./badge/badge.js";
import type { RowanBreadcrumb } from "./breadcrumb/breadcrumb.js";
import type { RowanButton } from "./button/button.js";
import type { RowanCalendar } from "./calendar/calendar.js";
import type { RowanCard } from "./card/card.js";
import type { RowanCheckbox } from "./checkbox/checkbox.js";
import type { RowanChip } from "./chip/chip.js";
import type { RowanCombobox } from "./combobox/combobox.js";
import type { RowanDatePicker } from "./date-picker/date-picker.js";
import type { RowanDateRangePicker } from "./date-range-picker/date-range-picker.js";
import type { RowanDivider } from "./divider/divider.js";
import type { RowanDialog } from "./dialog/dialog.js";
import type { RowanDropzone } from "./dropzone/dropzone.js";
import type { RowanDrawer } from "./drawer/drawer.js";
import type { RowanDropdown } from "./dropdown/dropdown.js";
import type { RowanEmptyState } from "./empty-state/empty-state.js";
import type { RowanFileItem } from "./file-item/file-item.js";
import type { RowanFileUpload } from "./file-upload/file-upload.js";
import type { RowanIconButton } from "./icon-button/icon-button.js";
import type { RowanLink } from "./link/link.js";
import type { RowanMenu } from "./menu/menu.js";
import type { RowanMenuItem } from "./menu-item/menu-item.js";
import type { RowanNumberField } from "./number-field/number-field.js";
import type { RowanPagination } from "./pagination/pagination.js";
import type { RowanPopover } from "./popover/popover.js";
import type { RowanProgress } from "./progress/progress.js";
import type { RowanRadio } from "./radio/radio.js";
import type { RowanRadioGroup } from "./radio-group/radio-group.js";
import type { RowanSelect } from "./select/select.js";
import type { RowanSkeleton } from "./skeleton/skeleton.js";
import type { RowanSpinner } from "./spinner/spinner.js";
import type { RowanStepper } from "./stepper/stepper.js";
import type { RowanSwitch } from "./switch/switch.js";
import type { RowanTab } from "./tab/tab.js";
import type { RowanTabPanel } from "./tab-panel/tab-panel.js";
import type { RowanTable } from "./table/table.js";
import type { RowanTabs } from "./tabs/tabs.js";
import type { RowanTextField } from "./text-field/text-field.js";
import type { RowanTextarea } from "./textarea/textarea.js";
import type { RowanTimePicker } from "./time-picker/time-picker.js";
import type { RowanToast } from "./toast/toast.js";
import type { RowanToaster } from "./toaster/toaster.js";
import type { RowanTooltip } from "./tooltip/tooltip.js";
import type { RowanValidationSummary } from "./validation-summary/validation-summary.js";

declare global {
  interface HTMLElementTagNameMap {
    "rowan-accordion": RowanAccordion;
    "rowan-alert": RowanAlert;
    "rowan-avatar": RowanAvatar;
    "rowan-badge": RowanBadge;
    "rowan-breadcrumb": RowanBreadcrumb;
    "rowan-button": RowanButton;
    "rowan-calendar": RowanCalendar;
    "rowan-card": RowanCard;
    "rowan-checkbox": RowanCheckbox;
    "rowan-chip": RowanChip;
    "rowan-combobox": RowanCombobox;
    "rowan-date-picker": RowanDatePicker;
    "rowan-date-range-picker": RowanDateRangePicker;
    "rowan-divider": RowanDivider;
    "rowan-dialog": RowanDialog;
    "rowan-dropzone": RowanDropzone;
    "rowan-drawer": RowanDrawer;
    "rowan-dropdown": RowanDropdown;
    "rowan-empty-state": RowanEmptyState;
    "rowan-file-item": RowanFileItem;
    "rowan-file-upload": RowanFileUpload;
    "rowan-icon-button": RowanIconButton;
    "rowan-link": RowanLink;
    "rowan-menu": RowanMenu;
    "rowan-menu-item": RowanMenuItem;
    "rowan-number-field": RowanNumberField;
    "rowan-pagination": RowanPagination;
    "rowan-popover": RowanPopover;
    "rowan-progress": RowanProgress;
    "rowan-radio": RowanRadio;
    "rowan-radio-group": RowanRadioGroup;
    "rowan-select": RowanSelect;
    "rowan-skeleton": RowanSkeleton;
    "rowan-spinner": RowanSpinner;
    "rowan-stepper": RowanStepper;
    "rowan-switch": RowanSwitch;
    "rowan-tab": RowanTab;
    "rowan-tab-panel": RowanTabPanel;
    "rowan-table": RowanTable;
    "rowan-tabs": RowanTabs;
    "rowan-text-field": RowanTextField;
    "rowan-textarea": RowanTextarea;
    "rowan-time-picker": RowanTimePicker;
    "rowan-toast": RowanToast;
    "rowan-toaster": RowanToaster;
    "rowan-tooltip": RowanTooltip;
    "rowan-validation-summary": RowanValidationSummary;
  }
}

export {};
