import type { RowanAlert } from "../types/alert/alert.js";
import type { RowanAreaChart } from "../types/area-chart/area-chart.js";
import type { RowanAccordion } from "../types/accordion/accordion.js";
import type { RowanAppLayout } from "../types/app-layout/app-layout.js";
import type { RowanAvatar } from "../types/avatar/avatar.js";
import type { RowanBadge } from "../types/badge/badge.js";
import type { RowanBarChart } from "../types/bar-chart/bar-chart.js";
import type { RowanBreadcrumb } from "../types/breadcrumb/breadcrumb.js";
import type { RowanBulkActionsBar } from "../types/bulk-actions-bar/bulk-actions-bar.js";
import type { RowanBulletChart } from "../types/bullet-chart/bullet-chart.js";
import type { RowanButton } from "../types/button/button.js";
import type { RowanFilterBuilder } from "../types/filter-builder/filter-builder.js";
import type { RowanCalendar } from "../types/calendar/calendar.js";
import type { RowanCarousel } from "../types/carousel/carousel.js";
import type { RowanColorPicker } from "../types/color-picker/color-picker.js";
import type { RowanCard } from "../types/card/card.js";
import type { RowanCheckbox } from "../types/checkbox/checkbox.js";
import type { RowanChip } from "../types/chip/chip.js";
import type { RowanCombobox } from "../types/combobox/combobox.js";
import type { RowanCommandItem } from "../types/command-item/command-item.js";
import type { RowanCommandPalette } from "../types/command-palette/command-palette.js";
import type { RowanConfirmDialog } from "../types/confirm-dialog/confirm-dialog.js";
import type { RowanContextMenu } from "../types/context-menu/context-menu.js";
import type { RowanDatePicker } from "../types/date-picker/date-picker.js";
import type { RowanDateRangePicker } from "../types/date-range-picker/date-range-picker.js";
import type { RowanDivider } from "../types/divider/divider.js";
import type { RowanDonutChart } from "../types/donut-chart/donut-chart.js";
import type { RowanDialog } from "../types/dialog/dialog.js";
import type { RowanDropzone } from "../types/dropzone/dropzone.js";
import type { RowanDrawer } from "../types/drawer/drawer.js";
import type { RowanDropdown } from "../types/dropdown/dropdown.js";
import type { RowanDataState } from "../types/data-state/data-state.js";
import type { RowanEmptyState } from "../types/empty-state/empty-state.js";
import type { RowanFileItem } from "../types/file-item/file-item.js";
import type { RowanFileUpload } from "../types/file-upload/file-upload.js";
import type { RowanFormField } from "../types/form-field/form-field.js";
import type { RowanFormLayout } from "../types/form-layout/form-layout.js";
import type { RowanFormWizard } from "../types/form-wizard/form-wizard.js";
import type { RowanGaugeChart } from "../types/gauge-chart/gauge-chart.js";
import type { RowanIconButton } from "../types/icon-button/icon-button.js";
import type { RowanImage } from "../types/image/image.js";
import type { RowanKpiCard } from "../types/kpi-card/kpi-card.js";
import type { RowanLink } from "../types/link/link.js";
import type { RowanListbox } from "../types/listbox/listbox.js";
import type { RowanMenu } from "../types/menu/menu.js";
import type { RowanMenuItem } from "../types/menu-item/menu-item.js";
import type { RowanMultiSelectCombobox } from "../types/multi-select-combobox/multi-select-combobox.js";
import type { RowanNumberField } from "../types/number-field/number-field.js";
import type { RowanOption } from "../types/option/option.js";
import type { RowanPagination } from "../types/pagination/pagination.js";
import type { RowanPopover } from "../types/popover/popover.js";
import type { RowanProgress } from "../types/progress/progress.js";
import type { RowanRadio } from "../types/radio/radio.js";
import type { RowanRadioGroup } from "../types/radio-group/radio-group.js";
import type { RowanRating } from "../types/rating/rating.js";
import type { RowanRichTextEditor } from "../types/rich-text-editor/rich-text-editor.js";
import type { RowanRowDetailsPanel } from "../types/row-details-panel/row-details-panel.js";
import type { RowanSelect } from "../types/select/select.js";
import type { RowanSegmentedControl } from "../types/segmented-control/segmented-control.js";
import type { RowanSideNav } from "../types/side-nav/side-nav.js";
import type { RowanSideNavItem } from "../types/side-nav-item/side-nav-item.js";
import type { RowanSideNavSection } from "../types/side-nav-section/side-nav-section.js";
import type { RowanSkeleton } from "../types/skeleton/skeleton.js";
import type { RowanSlider } from "../types/slider/slider.js";
import type { RowanSourceMeta } from "../types/source-meta/source-meta.js";
import type { RowanSparkline } from "../types/sparkline/sparkline.js";
import type { RowanSpinner } from "../types/spinner/spinner.js";
import type { RowanStackedBarChart } from "../types/stacked-bar-chart/stacked-bar-chart.js";
import type { RowanSplitPane } from "../types/split-pane/split-pane.js";
import type { RowanStatusIndicator } from "../types/status-indicator/status-indicator.js";
import type { RowanStepper } from "../types/stepper/stepper.js";
import type { RowanSwitch } from "../types/switch/switch.js";
import type { RowanTab } from "../types/tab/tab.js";
import type { RowanTabPanel } from "../types/tab-panel/tab-panel.js";
import type { RowanTable } from "../types/table/table.js";
import type { RowanTableToolbar } from "../types/table-toolbar/table-toolbar.js";
import type { RowanTabs } from "../types/tabs/tabs.js";
import type { RowanTrendChart } from "../types/trend-chart/trend-chart.js";
import type { RowanTree } from "../types/tree/tree.js";
import type { RowanTreeItem } from "../types/tree-item/tree-item.js";
import type { RowanTextField } from "../types/text-field/text-field.js";
import type { RowanTextarea } from "../types/textarea/textarea.js";
import type { RowanTimePicker } from "../types/time-picker/time-picker.js";
import type { RowanToast } from "../types/toast/toast.js";
import type { RowanToaster } from "../types/toaster/toaster.js";
import type { RowanTooltip } from "../types/tooltip/tooltip.js";
import type { RowanValidationSummary } from "../types/validation-summary/validation-summary.js";
import type { RowanVirtualList } from "../types/virtual-list/virtual-list.js";

declare global {
  interface HTMLElementTagNameMap {
    "rowan-accordion": RowanAccordion;
    "rowan-alert": RowanAlert;
    "rowan-area-chart": RowanAreaChart;
    "rowan-app-layout": RowanAppLayout;
    "rowan-avatar": RowanAvatar;
    "rowan-badge": RowanBadge;
    "rowan-bar-chart": RowanBarChart;
    "rowan-breadcrumb": RowanBreadcrumb;
    "rowan-bulk-actions-bar": RowanBulkActionsBar;
    "rowan-bullet-chart": RowanBulletChart;
    "rowan-button": RowanButton;
    "rowan-filter-builder": RowanFilterBuilder;
    "rowan-calendar": RowanCalendar;
    "rowan-carousel": RowanCarousel;
    "rowan-color-picker": RowanColorPicker;
    "rowan-card": RowanCard;
    "rowan-checkbox": RowanCheckbox;
    "rowan-chip": RowanChip;
    "rowan-combobox": RowanCombobox;
    "rowan-command-item": RowanCommandItem;
    "rowan-command-palette": RowanCommandPalette;
    "rowan-confirm-dialog": RowanConfirmDialog;
    "rowan-context-menu": RowanContextMenu;
    "rowan-date-picker": RowanDatePicker;
    "rowan-date-range-picker": RowanDateRangePicker;
    "rowan-divider": RowanDivider;
    "rowan-donut-chart": RowanDonutChart;
    "rowan-dialog": RowanDialog;
    "rowan-dropzone": RowanDropzone;
    "rowan-drawer": RowanDrawer;
    "rowan-dropdown": RowanDropdown;
    "rowan-data-state": RowanDataState;
    "rowan-empty-state": RowanEmptyState;
    "rowan-file-item": RowanFileItem;
    "rowan-file-upload": RowanFileUpload;
    "rowan-form-field": RowanFormField;
    "rowan-form-layout": RowanFormLayout;
    "rowan-form-wizard": RowanFormWizard;
    "rowan-gauge-chart": RowanGaugeChart;
    "rowan-icon-button": RowanIconButton;
    "rowan-image": RowanImage;
    "rowan-kpi-card": RowanKpiCard;
    "rowan-link": RowanLink;
    "rowan-listbox": RowanListbox;
    "rowan-menu": RowanMenu;
    "rowan-menu-item": RowanMenuItem;
    "rowan-multi-select-combobox": RowanMultiSelectCombobox;
    "rowan-number-field": RowanNumberField;
    "rowan-option": RowanOption;
    "rowan-pagination": RowanPagination;
    "rowan-popover": RowanPopover;
    "rowan-progress": RowanProgress;
    "rowan-radio": RowanRadio;
    "rowan-radio-group": RowanRadioGroup;
    "rowan-rating": RowanRating;
    "rowan-rich-text-editor": RowanRichTextEditor;
    "rowan-row-details-panel": RowanRowDetailsPanel;
    "rowan-select": RowanSelect;
    "rowan-segmented-control": RowanSegmentedControl;
    "rowan-side-nav": RowanSideNav;
    "rowan-side-nav-item": RowanSideNavItem;
    "rowan-side-nav-section": RowanSideNavSection;
    "rowan-skeleton": RowanSkeleton;
    "rowan-slider": RowanSlider;
    "rowan-source-meta": RowanSourceMeta;
    "rowan-sparkline": RowanSparkline;
    "rowan-spinner": RowanSpinner;
    "rowan-stacked-bar-chart": RowanStackedBarChart;
    "rowan-split-pane": RowanSplitPane;
    "rowan-status-indicator": RowanStatusIndicator;
    "rowan-stepper": RowanStepper;
    "rowan-switch": RowanSwitch;
    "rowan-tab": RowanTab;
    "rowan-tab-panel": RowanTabPanel;
    "rowan-table": RowanTable;
    "rowan-table-toolbar": RowanTableToolbar;
    "rowan-tabs": RowanTabs;
    "rowan-trend-chart": RowanTrendChart;
    "rowan-tree": RowanTree;
    "rowan-tree-item": RowanTreeItem;
    "rowan-text-field": RowanTextField;
    "rowan-textarea": RowanTextarea;
    "rowan-time-picker": RowanTimePicker;
    "rowan-toast": RowanToast;
    "rowan-toaster": RowanToaster;
    "rowan-tooltip": RowanTooltip;
    "rowan-validation-summary": RowanValidationSummary;
    "rowan-virtual-list": RowanVirtualList;
  }
}

export {};
