// Generated from src/** DEFAULT_MESSAGES by scripts/sync-message-catalog.mjs. Do not edit directly.
export const ROWAN_MESSAGE_CATALOG = [
  {
    tag: "rowan-alert",
    module: "alert",
    keys: ["dismissLabel"],
  },
  {
    tag: "rowan-app-layout",
    module: "app-layout",
    keys: ["navigationToggle"],
  },
  {
    tag: "rowan-area-chart",
    module: "area-chart",
    keys: [
      "chart",
      "dataTable",
      "dataTableCaption",
      "metric",
      "noData",
      "noMetricData",
      "point",
      "reference",
      "series",
    ],
  },
  {
    tag: "rowan-avatar",
    module: "avatar",
    keys: ["avatar"],
  },
  {
    tag: "rowan-bar-chart",
    module: "bar-chart",
    keys: [
      "chart",
      "dataTable",
      "dataTableCaption",
      "metric",
      "noData",
      "point",
      "reference",
      "series",
    ],
  },
  {
    tag: "rowan-box-plot-chart",
    module: "box-plot-chart",
    keys: [
      "category",
      "chart",
      "dataTable",
      "dataTableCaption",
      "max",
      "maxValue",
      "median",
      "medianValue",
      "min",
      "minValue",
      "noData",
      "outliers",
      "point",
      "q1",
      "q1Value",
      "q3",
      "q3Value",
      "series",
    ],
  },
  {
    tag: "rowan-breadcrumb",
    module: "breadcrumb",
    keys: ["navigationLabel"],
  },
  {
    tag: "rowan-bulk-actions-bar",
    module: "bulk-actions-bar",
    keys: ["clearLabel", "label", "selectionLabel", "selectionStatus"],
  },
  {
    tag: "rowan-bullet-chart",
    module: "bullet-chart",
    keys: ["actual", "chart", "noData", "range", "target"],
  },
  {
    tag: "rowan-calendar",
    module: "calendar",
    keys: ["dayLabel", "nextMonth", "nextMonthLabel", "previousMonth", "previousMonthLabel"],
  },
  {
    tag: "rowan-carousel",
    module: "carousel",
    keys: ["emptyStatus", "nextPanel", "panelStatus", "previousPanel", "roleDescription"],
  },
  {
    tag: "rowan-color-picker",
    module: "color-picker",
    keys: [
      "customColor",
      "customColorLabel",
      "opacity",
      "opacityLabel",
      "paletteLabel",
      "pickerLabel",
      "swatchLabel",
    ],
  },
  {
    tag: "rowan-combo-chart",
    module: "combo-chart",
    keys: [
      "chart",
      "dataTable",
      "dataTableCaption",
      "metric",
      "noData",
      "point",
      "reference",
      "series",
    ],
  },
  {
    tag: "rowan-combobox",
    module: "combobox",
    keys: ["noMatchingOptions"],
  },
  {
    tag: "rowan-command-palette",
    module: "command-palette",
    keys: ["close", "emptyLabel", "label", "placeholder"],
  },
  {
    tag: "rowan-confirm-dialog",
    module: "confirm-dialog",
    keys: ["cancelLabel", "confirmLabel", "label"],
  },
  {
    tag: "rowan-context-menu",
    module: "context-menu",
    keys: ["label"],
  },
  {
    tag: "rowan-data-state",
    module: "data-state",
    keys: ["empty", "error", "loading"],
  },
  {
    tag: "rowan-date-range-picker",
    module: "date-range-picker",
    keys: ["clear", "end", "rangeEndpoint", "separator", "start"],
  },
  {
    tag: "rowan-dialog",
    module: "dialog",
    keys: ["closeLabel", "title"],
  },
  {
    tag: "rowan-donut-chart",
    module: "donut-chart",
    keys: [
      "chart",
      "dataTable",
      "dataTableCaption",
      "metric",
      "noData",
      "point",
      "reference",
      "slices",
      "total",
    ],
  },
  {
    tag: "rowan-drawer",
    module: "drawer",
    keys: ["close", "closeLabel", "title"],
  },
  {
    tag: "rowan-dropzone",
    module: "dropzone",
    keys: ["ariaLabel", "description", "label"],
  },
  {
    tag: "rowan-file-item",
    module: "file-item",
    keys: [
      "cancel",
      "fileSize",
      "remove",
      "retry",
      "statusFailed",
      "statusQueued",
      "statusSuccess",
      "statusUploading",
      "untitledFile",
      "uploadProgress",
    ],
  },
  {
    tag: "rowan-file-upload",
    module: "file-upload",
    keys: [
      "ariaLabel",
      "dropzoneDescription",
      "dropzoneLabel",
      "empty",
      "itemCancel",
      "itemFileSize",
      "itemRemove",
      "itemRetry",
      "itemStatusFailed",
      "itemStatusQueued",
      "itemStatusSuccess",
      "itemStatusUploading",
      "itemUntitledFile",
      "itemUploadProgress",
    ],
  },
  {
    tag: "rowan-filter-builder",
    module: "filter-builder",
    keys: [
      "addGroupLabel",
      "addInGroupLabel",
      "addLabel",
      "booleanFalse",
      "booleanTrue",
      "chooseValue",
      "clearLabel",
      "empty",
      "fieldLabel",
      "groupJoinAnd",
      "groupJoinLabel",
      "groupJoinOr",
      "label",
      "noValue",
      "operatorLabel",
      "operatorSelectLabel",
      "remove",
      "removeFilter",
      "removeGroup",
      "unknownField",
      "value",
      "valueFor",
    ],
  },
  {
    tag: "rowan-form-field",
    module: "form-field",
    keys: ["required"],
  },
  {
    tag: "rowan-form-wizard",
    module: "form-wizard",
    keys: [
      "completeLabel",
      "label",
      "nextLabel",
      "previousLabel",
      "stepLabel",
      "thisField",
      "validationEmpty",
      "validationErrorItem",
      "validationFieldInvalid",
      "validationHeading",
      "validationUnnamedField",
    ],
  },
  {
    tag: "rowan-funnel-chart",
    module: "funnel-chart",
    keys: ["chart", "dataTable", "dataTableCaption", "metric", "noData", "point", "stages"],
  },
  {
    tag: "rowan-gauge-chart",
    module: "gauge-chart",
    keys: ["actual", "chart", "maximum", "minimum", "noData", "range", "target"],
  },
  {
    tag: "rowan-heatmap-chart",
    module: "heatmap-chart",
    keys: ["chart", "column", "dataTable", "dataTableCaption", "noData", "row"],
  },
  {
    tag: "rowan-kpi-card",
    module: "kpi-card",
    keys: ["deltaWithLabel", "kpi", "noData"],
  },
  {
    tag: "rowan-multi-select-combobox",
    module: "multi-select-combobox",
    keys: ["noMatchingOptions", "optionsForLabel", "optionsLabel", "placeholder", "removeOption"],
  },
  {
    tag: "rowan-number-field",
    module: "number-field",
    keys: ["decreaseValue", "increaseValue"],
  },
  {
    tag: "rowan-pagination",
    module: "pagination",
    keys: ["navigationLabel", "nextPage", "pageStatus", "previousPage"],
  },
  {
    tag: "rowan-popover",
    module: "popover",
    keys: ["label"],
  },
  {
    tag: "rowan-progress",
    module: "progress",
    keys: ["labeledValueText", "progress", "valueText"],
  },
  {
    tag: "rowan-radar-chart",
    module: "radar-chart",
    keys: ["chart", "dataTable", "dataTableCaption", "metric", "noData", "point", "series"],
  },
  {
    tag: "rowan-range-chart",
    module: "range-chart",
    keys: [
      "category",
      "chart",
      "dataTable",
      "dataTableCaption",
      "high",
      "highValue",
      "low",
      "lowValue",
      "noData",
      "point",
      "series",
    ],
  },
  {
    tag: "rowan-rating",
    module: "rating",
    keys: ["clearRating", "noRatingSelected", "rating", "ratingValue", "starValue"],
  },
  {
    tag: "rowan-rich-text-editor",
    module: "rich-text-editor",
    keys: [
      "apply",
      "bold",
      "bulletedList",
      "heading",
      "italic",
      "link",
      "linkUrl",
      "numberedList",
      "remove",
      "richTextEditor",
      "textFormatting",
      "toolbarLabel",
      "underline",
      "url",
      "urlPlaceholder",
    ],
  },
  {
    tag: "rowan-row-details-panel",
    module: "row-details-panel",
    keys: ["empty", "nextRow", "notSet", "pagerStatus", "previousRow"],
  },
  {
    tag: "rowan-scatter-chart",
    module: "scatter-chart",
    keys: [
      "chart",
      "dataTable",
      "dataTableCaption",
      "noData",
      "point",
      "pointLabel",
      "series",
      "size",
      "sizeValue",
      "x",
      "xValue",
      "y",
      "yValue",
    ],
  },
  {
    tag: "rowan-slider",
    module: "slider",
    keys: ["end", "rangeEndpoint", "rangeValue", "start", "value"],
  },
  {
    tag: "rowan-source-meta",
    module: "source-meta",
    keys: ["asOf"],
  },
  {
    tag: "rowan-sparkline",
    module: "sparkline",
    keys: ["chart", "noData", "point"],
  },
  {
    tag: "rowan-spinner",
    module: "spinner",
    keys: ["loading"],
  },
  {
    tag: "rowan-split-pane",
    module: "split-pane",
    keys: ["resizePanes", "valueText"],
  },
  {
    tag: "rowan-stacked-area-chart",
    module: "stacked-area-chart",
    keys: [
      "chart",
      "dataTable",
      "dataTableCaption",
      "metric",
      "noData",
      "point",
      "reference",
      "series",
    ],
  },
  {
    tag: "rowan-stacked-bar-chart",
    module: "stacked-bar-chart",
    keys: [
      "chart",
      "dataTable",
      "dataTableCaption",
      "metric",
      "noData",
      "point",
      "reference",
      "series",
    ],
  },
  {
    tag: "rowan-stepper",
    module: "stepper",
    keys: ["stepLabel"],
  },
  {
    tag: "rowan-table",
    module: "table",
    keys: [
      "action",
      "checkbox",
      "empty",
      "emptyGroup",
      "groupLabel",
      "loading",
      "nextPage",
      "paginationEmpty",
      "paginationLabel",
      "paginationStatus",
      "previousPage",
      "selectAllRows",
      "selectRow",
      "subtotal",
      "switch",
    ],
  },
  {
    tag: "rowan-table-toolbar",
    module: "table-toolbar",
    keys: ["columnPickerLabel", "selectionStatus", "visibleColumnsLabel"],
  },
  {
    tag: "rowan-toast",
    module: "toast",
    keys: ["dismiss", "dismissLabel"],
  },
  {
    tag: "rowan-trend-chart",
    module: "trend-chart",
    keys: [
      "chart",
      "dataTable",
      "dataTableCaption",
      "metric",
      "noData",
      "noMetricData",
      "point",
      "reference",
      "series",
    ],
  },
  {
    tag: "rowan-validation-summary",
    module: "validation-summary",
    keys: ["empty", "errorItem", "fieldInvalid", "heading", "unnamedField"],
  },
  {
    tag: "rowan-waterfall-chart",
    module: "waterfall-chart",
    keys: [
      "category",
      "chart",
      "dataTable",
      "dataTableCaption",
      "decrease",
      "deltaValue",
      "encodings",
      "increase",
      "noData",
      "point",
      "total",
      "totalValue",
      "type",
      "value",
    ],
  },
];
